#!/bin/bash
# Generated by LockChain v{{VERSION}}

DATASETS_STR="{{DATASETS}}"
MAPPINGS_STR="{{MAPPINGS}}"

depends() {
    echo systemd
    if [[ -n "${DATASETS_STR// }" ]] && command -v zfs >/dev/null 2>&1; then
        echo zfs
    fi
    return 0
}

install() {
    inst_multiple blkid mount umount mkdir mountpoint sha256sum udevadm stat
    instmods ext4 vfat nls_utf8

    inst_simple "$moddir/run-lockchain.mount" "$systemdsystemunitdir/run-lockchain.mount"

    if [[ -n "${DATASETS_STR// }" ]]; then
        inst_simple "$moddir/{{SCRIPT_NAME}}" "/sbin/{{SCRIPT_NAME}}"
        inst_simple "$moddir/{{SERVICE_NAME}}" "$systemdsystemunitdir/{{SERVICE_NAME}}"
        mkdir -p "$systemdsystemunitdir/zfs-load-key.service.d"
        inst_simple "$moddir/{{DROPIN_DIR}}/{{DROPIN_NAME}}" "$systemdsystemunitdir/zfs-load-key.service.d/{{DROPIN_NAME}}"
        mkdir -p "$systemdsystemunitdir/{{MODULE_DROPIN_DIR}}"
        inst_simple "$moddir/{{MODULE_DROPIN_DIR}}/{{DROPIN_NAME}}" "$systemdsystemunitdir/{{MODULE_DROPIN_DIR}}/{{DROPIN_NAME}}"
        mkdir -p "$systemdsystemunitdir/initrd-root-fs.target.wants"
        ln -sf "../{{SERVICE_NAME}}" "$systemdsystemunitdir/initrd-root-fs.target.wants/{{SERVICE_NAME}}"
    fi

    if [[ -n "${MAPPINGS_STR// }" ]]; then
        inst_simple "$moddir/lockchain-cryptsetup-keys.sh" "/sbin/lockchain-cryptsetup-keys.sh"
        inst_simple "$moddir/lockchain-cryptsetup-keys.service" "$systemdsystemunitdir/lockchain-cryptsetup-keys.service"
        mkdir -p "$systemdsystemunitdir/systemd-cryptsetup@.service.d"
        inst_simple "$moddir/systemd-cryptsetup@.service.d/lockchain.conf" "$systemdsystemunitdir/systemd-cryptsetup@.service.d/lockchain.conf"
        mkdir -p "$systemdsystemunitdir/initrd-root-fs.target.wants"
        ln -sf "../lockchain-cryptsetup-keys.service" "$systemdsystemunitdir/initrd-root-fs.target.wants/lockchain-cryptsetup-keys.service"
    fi

    mkdir -p "$systemdsystemunitdir/initrd-root-fs.target.wants"
    ln -sf "../run-lockchain.mount" "$systemdsystemunitdir/initrd-root-fs.target.wants/run-lockchain.mount"
}
